#include <Arduino.h>
#include <LiquidCrystal_I2C.h>
#include <MIDI.h>

#include "Standard.h"
#include "I2C_EEPROM.h"
#include "Nav.h"
#include "Button.h"
#include "Knob.h"
#include "ShiftRegisterPWM.h"
#include "LED.h"
#include "LCD.h"
#include "Hardware.h"
#include "Database.h"
#include "Callbacks.h"
#include "TextEdit.h"
#include "ValueEdit.h"
#include "ColorEdit.h"
#include "Confirm.h"
#include "MenuSystem.h"
#include "Midi.h"
#include "Load_EEPROM.h"
#include "Alt_Program.h"
